"""Rasterizes the 2026 catalogues into spreads the browser can read (Part I.3).

    python scripts/rasterize-catalogues.py

Part I is explicit that the catalogue experience is not a PDF viewer. The three
PDFs are 8, 24 and 70 MB of print-resolution artwork; nobody is reading that on
a phone in a machine hall. So every page is rasterized once at build time into a
WebP spread plus a thumbnail, and the reader lazy-loads a window around the page
you are actually on.

It also extracts each page's text into a search index (Part I.5) and records
which catalogue model codes appear on which page, which is what lets a spread
offer "Explore in 3D" without anyone hand-tagging 48 pages. Where a page carries
no extractable text — the Bow Way catalogue is largely placed artwork — it
simply contributes nothing to the index rather than being guessed at.

Output: public/catalogue/<doc>/<n>.webp, thumb-<n>.webp, and
content/catalogue/generated.json. Never edit that file by hand.
"""

import io
import json
import re
from pathlib import Path

import fitz
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "public" / "docs"
OUT = ROOT / "public" / "catalogue"
MANIFEST = ROOT / "content" / "catalogue" / "generated.json"

# 2x the largest sensible display width. Beyond this the file grows faster than
# the page becomes readable, which is the wrong trade on hall wifi (Part O).
SPREAD_WIDTH = 2000
THUMB_WIDTH = 240
SPREAD_QUALITY = 78
THUMB_QUALITY = 62

# Catalogue model codes, so a spread can offer the machine it shows.
MODEL_PATTERN = re.compile(r"\bKMC-(\d{3,4}(?:GM|GN|HMA|HA14|HA11|H11|CE|CH))\b", re.I)

DOCUMENTS = [
    {
        "id": "cat-gn-gm-2026-en",
        "file": "KMC-GN-GM-Gantry-Series-2026-EN.pdf",
        "covers": ["kmc-gm", "kmc-gn"],
    },
    {
        "id": "cat-bow-way-2026-en",
        "file": "KMC-Bow-Way-Hephaestus-Minerva-2026-EN.pdf",
        "covers": ["kmc-h7-h8", "kmc-h11", "kmc-ha11", "kmc-ha14", "kmc-hma"],
    },
    {
        "id": "cat-clymene-2026-en",
        "file": "KMC-CE-CH-Clymene-Vertical-2026-EN.pdf",
        "covers": ["kmc-ce", "kmc-ch"],
    },
]


def save_webp(pixmap, destination: Path, width: int, quality: int) -> tuple[int, int]:
    image = Image.open(io.BytesIO(pixmap.tobytes("png"))).convert("RGB")
    if image.width > width:
        height = round(image.height * width / image.width)
        image = image.resize((width, height), Image.LANCZOS)
    destination.parent.mkdir(parents=True, exist_ok=True)
    image.save(destination, "WEBP", quality=quality, method=6)
    return image.width, image.height


def clean(text: str) -> str:
    """Collapse the PDF's line breaks so a search for two words can match."""
    return re.sub(r"\s+", " ", text).strip()


documents = []

for document in DOCUMENTS:
    source = DOCS / document["file"]
    if not source.exists():
        print(f"  missing {document['file']}")
        continue

    pdf = fitz.open(source)
    directory = OUT / document["id"]
    pages = []

    print(f"{document['id']}: {pdf.page_count} pages")

    for number, page in enumerate(pdf, start=1):
        # The zoom that lands closest to SPREAD_WIDTH without going under it.
        zoom = max(SPREAD_WIDTH / page.rect.width, 1.0)
        pixmap = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=False)

        width, height = save_webp(
            pixmap, directory / f"{number}.webp", SPREAD_WIDTH, SPREAD_QUALITY
        )
        save_webp(pixmap, directory / f"thumb-{number}.webp", THUMB_WIDTH, THUMB_QUALITY)

        text = clean(page.get_text())
        models = sorted({match.group(1).upper() for match in MODEL_PATTERN.finditer(text)})

        pages.append(
            {
                "page": number,
                "src": f"/catalogue/{document['id']}/{number}.webp",
                "thumb": f"/catalogue/{document['id']}/thumb-{number}.webp",
                "width": width,
                "height": height,
                # Trimmed: the index is for finding a page, not for reading it.
                "text": text[:1200],
                "models": models,
            }
        )

    documents.append(
        {
            "id": document["id"],
            "covers": document["covers"],
            "pdf": f"/docs/{document['file']}",
            "pageCount": len(pages),
            "pages": pages,
        }
    )
    pdf.close()

MANIFEST.parent.mkdir(parents=True, exist_ok=True)
MANIFEST.write_text(
    json.dumps(
        {
            "note": "Generated by scripts/rasterize-catalogues.py from the 2026 PDFs. "
            "Do not edit by hand.",
            "documents": documents,
        },
        ensure_ascii=False,
        indent=1,
    )
    + "\n",
    encoding="utf-8",
)

total = sum(doc["pageCount"] for doc in documents)
print(f"\n{total} spreads written to public/catalogue/")
